Add option to avoid making a database connection during install.
paper-trail-gem/paper_trail pull request #1308
Opened 2021-04-12 15:22 UTC by acesuares

Add option --with-mysql
Prevents the installer form making a database connection during install.
If false (default) the database type will be determined automatically at the cost of a database connection, which might not be available at install time."

Thank you for your contribution!

Check the following boxes:

- [X ] Wrote [good commit messages][1].
- [ X] Feature branch is up-to-date with `master` (if not - rebase it).
- [ X] Squashed related commits together.
- [O] Added tests.
- [X ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [X ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/

2021-04-12 16:17 UTC, jaredbeck requested changes
Hi Ace, thanks for the contribution. 

Instead of a new option, could we get this information from `:adapter` in `ActiveRecord::DatabaseConfigurations`?

2021-04-12 16:28 UTC, acesuares commented
Dear Jared, I have no idea if that's possible. If it is, great! 
I just want to avoid making that database connection in cases where the database is not setup at the time of install.

2021-04-12 16:36 UTC, jaredbeck commented
> Dear Jared, I have no idea if that's possible. If it is, great!

I'd like to see this alternative researched before I consider this new feature further, thanks.

2021-04-12 17:57 UTC, acesuares commented
Not sure if I am able to do that.

`ActiveRecord::Base.configurations[]['adapter'] => "mysql2" `

2021-04-12 18:12 UTC, acesuares commented
in Rails 6.1 is should be
ActiveRecord::Base.configurations.configs_for(env_name: 'development').first.adapter

2021-07-19 01:46 UTC, closed without merging

2021-07-19 16:03 UTC, acesuares commented
Dear, I researched the item to the best of my capabilities. Is it possible for you to implement it?